micronaut:
  application:
    name: myapp
  session:
    http:
      cookie: true
      header: true
datasources:
  default:
    driverClassName: org.postgresql.Driver
    db-type: postgres
    schema-generate: CREATE_DROP
    dialect: POSTGRES
netty:
  default:
    allocator:
      max-order: 3
